
save_dir: null  # where to save trained models (default e.g. wdir/quijotelike/fastpm/models)

halo: False      # whether to train on halo summaries
galaxy: False    # whether to train on galaxy summaries
ngc_lightcone: False # whether to train on ngc_lightcone summaries
sgc_lightcone: False # whether to train on sgc_lightcone summaries
mtng_lightcone: False # whether to train on mtng_lightcone summaries

Nmax: -1  # maximum number of simulations to load (-1 for all)
Nnets: 10  # number of best networks to ensemble

val_frac: 0.1  # fraction of data to use for validation
test_frac: 0.1  # fraction of data to use for testing
seed: 0  # random seed for train/val/test split

prior: quijote  # prior to use for training (uniform, quijote_like)

backend: lampe # backend to use for training (sbi/lampe/pydelfi)
engine: NPE    # engine to use for training (NPE/NLE/NRE)

batch_size: 64  # batch size
learning_rate: 2e-5  # learning rate
stop_after_epochs: 50  # stop early after this many epochs
weight_decay: 0  # weight decay
lr_decay_factor: 0.5  # learning rate decay factor
lr_patience: 10  # learning rate decay patience

device: cpu  # cpu or cuda

exp_index: null  # index of experiment to run (null for all)
net_index: 0     # index of network to use in cfg.net

experiments:
  - summary: [Pk0]   # monopole
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [Pk0, Pk2]   # monopole, quadrupole
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [Pk0, Pk2, Pk4]   # monopole, quadrupole, hexadecapole
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [zPk0]   # monopole
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [zPk0, zPk2]   # monopole, quadrupole
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
  - summary: [zPk0, zPk2, zPk4]  # redshift-space monopole, quadrupole, hexadecapole
    kmax: [0.1, 0.2, 0.3, 0.4, 0.5]
