Nmax: 200
backend: sbi
batch_size: 64
device: cuda
engine: NPE
experiments:
- kmax:
  - 0.1
  summary:
  - Pk0
fcn_hidden:
- 64
- 32
- 16
galaxy: false
halo: true
learning_rate: 0.001
nets:
- hidden_features: 110
  model: mdn
  num_components: 2
- hidden_features: 47
  model: nsf
  num_transforms: 3
- hidden_features: 110
  model: maf
  num_transforms: 2
ngc_lightcone: false
prior: Uniform
save_dir: /anvil/scratch/x-dbartlett/cmass/quijotelike/fastpm/models_nets3_sims200
sgc_lightcone: false
test_frac: 0.1
val_frac: 0.1
